### ISSUE TITLE
Failed to fetch secret: 'secret_name'. Error: TimeoutError.

### ISSUE THREAD

**Issue by vijayvikama** [aws-actions/aws-secretsmanager-get-secrets#170]
Can someone help why i see intermittent timeouts . My session duratiuon is 1 hour at I am role. I am using OIDC with AWS

      - name: Get Secrets from AWS Secrets Manager
        id: get-secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            secret_name
          parse-json-secrets: true

Run aws-actions/aws-secretsmanager-get-secrets@v2
Building secrets list...
Your secret names may be transformed in order to be valid environment variables (see README). Enable Debug logging in order to view the new environment names.
Error: Failed to fetch secret: 'secret_name'. Error: TimeoutError.

**Comment by jirkafajfr** [comment]
Are you using self-hosted or github hosted runners? 

Would you mind sending me arn and exact timestamps when these timeouts happened? I would advise not publishing the ARN to the comment here, but sending via mail fajfr@amazon.com.

**Comment by javraj-trayio** [comment]
Any update on this? Seeing this all of a sudden in the ap-southeast-2 region

**Comment by justedro** [comment]
+1 the same issue there, reading secret in `ap-southeast-2` from `eu-west-1`

temporary workaround (for plaintext secrets)

```
      - name: Set up AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          rm -r awscliv2.zip ./aws

      - name: Get secret
        run: |
          secret_value=$(aws secretsmanager get-secret-value --secret-id "your/secret/name" --query 'SecretString' --output text)
          echo "SECRET=$secret_value" >> $GITHUB_ENV
```

**Comment by jirkafajfr** [comment]
The https://github.com/aws-actions/aws-secretsmanager-get-secrets/pull/205 should resolve the problem. Closing the ticket - please let me know if you continue to have problems.
