### ISSUE TITLE
getting permission denied issue if configure-aws-credentials has different region.

### ISSUE THREAD

**Issue by Pixis-Akshay-Gopani** [aws-actions/aws-secretsmanager-get-secrets#182]
-  we are getting permission denied issue when secret region is different than configured from configure-aws-credentials action. 
- ideally if someone pass entire aws secret arn then it should not use the region configured from configure-aws-credentials.

**Comment by simonmarty** [comment]
This is consistent with AWS Secrets Manager API behavior. Override this behavior using environment variables like `AWS_REGION` for ex.

```sh
# With us-west-2 credentials
aws secretsmanager describe-secret --secret-id arn:aws:secretsmanager:us-east-1:048373692869:secret:newsecret # fails
aws secretsmanager describe-secret --secret-id arn:aws:secretsmanager:us-east-1:048373692869:secret:newsecret --region us-east-1 # succeeds
```
