### ISSUE TITLE
net_1.setDefaultAutoSelectFamilyAttemptTimeout is not a function

### ISSUE THREAD

**Issue by ywang-psee** [aws-actions/aws-secretsmanager-get-secrets#206]
I encountered a problem while using `aws-actions/aws-secretsmanager-get-secrets@v2.0.7`.

**Error Message:**
```
Run aws-actions/aws-secretsmanager-get-secrets@v2
Run '/home/runner/k8s/index.js'
  shell: /home/runner/externals/node16/bin/node {0}
Error: (0 , net_1.setDefaultAutoSelectFamilyAttemptTimeout) is not a function
Error: Error: failed to run script step: command terminated with non-zero exit code: exit status 1
Error: Process completed with exit code 1.
Error: Executing the custom container implementation failed. Please contact your self hosted runner administrator.
```

**Environment Details**
- Action runner version: actions-runner: `2.320.0`
- Node.js version: `16`
- Custom container os: `ubuntu 18.04`
- Runner type: Self-hosted runner -> runner scale sets -> In Kubernetes mode
- Runner env:
  - `ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION=node16`
  - `ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION=node16`

**Workaround:**
Using `aws-actions/aws-secretsmanager-get-secrets@v2.0.6` resolves the issue.

**Comment by jirkafajfr** [comment]
Hi,

we've increased the dualstack resolution timeout (https://github.com/aws-actions/aws-secretsmanager-get-secrets/pull/205) to deal with intermittent timeouts where the runner and aws region are far away from each other. Our intention is to support Node 20 in `aws-actions/aws-secretsmanager-get-secrets@v2` where `setDefaultAutoSelectFamilyAttemptTimeout` is built-in function.

The `ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION` in your snippet is downgrading to the Node 16. The @v1 is still pinned to the Node 16. You should be using that if you insist on running Node 16.

Please note that [Node 16 reached End-of-Life on September 11th, 2023](https://nodejs.org/en/blog/announcements/nodejs16-eol) and [Github was running migration campaign to Node 20 during spring of 2024](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). 

We are not planning to support Node 16 on the `@v2`.

**Comment by ywang-psee** [comment]
Thank you for your reply!
