### ISSUE TITLE
Remove uppercase enforcement of environment variables

### ISSUE THREAD

**Issue by pcassaretto-cmc** [aws-actions/aws-secretsmanager-get-secrets#67]
Currently environment vars must be uppercase, which prevents us from populating terraform input variables directly with this action.  For example, we cannot do `TF_VAR_secret_1` directly with this action and then need an intermediate action to take this output and set the correct terraform environment variable.

I think this should be allowed given the enormous popularity of terraform.  Can't see any documented reasoning why you force the name to uppercase here https://github.com/aws-actions/aws-secretsmanager-get-secrets/blob/main/src/utils.ts#L189C54-L189C65

**Comment by jbct** [comment]
Thank you for the request, we will look into this.

**Comment by jirkafajfr** [comment]
We've added option `name-transformation`. Your use-case is covered by `name-transformation: none`. Please see the [documentaiton](https://docs.aws.amazon.com/secretsmanager/latest/userguide/retrieving-secrets_github.html) or https://github.com/aws-actions/aws-secretsmanager-get-secrets/pull/139 for more info.
